calendar_/urls.py
from django.urls import path
from .views import CalendarView, AddEventView, EventDetailView, EventEditView, EventDeleteView

urlpatterns = [
    path('calendar/', CalendarView.as_view(), name='calendar'),
    path('add_event/', AddEventView.as_view(), name='add_event'),
    path('event/<int:pk>/', EventDetailView.as_view(), name='event_detail'),
    path('event_edit/<int:pk>/', EventEditView.as_view(), name='event_edit'),
    path('event_delete/<int:pk>/', EventDeleteView.as_view(), name='event_delete'),
    ]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from trainingplans import views
from trainingplans.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('treningikonne/', include("trainingplans.urls")),
    path('kalendarz/', include("calendar_.urls")),
]

calendar_/models.py
from django.db import models
from django.contrib.auth.models import User


class Event(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    def __str__(self):
        return f"{self.title} start: {self.start_time} koniec: {self.end_time}"

calendar_/forms.py
from django import forms
from .models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'start_time', 'end_time']
        widgets = {
            'start_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class EventEditForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'start_time', 'end_time', 'description']
        widgets = {
            'start_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

calendar_/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from .models import Event
from .forms import EventForm, EventEditForm
from django.middleware.csrf import get_token


class CalendarView(View):
    def get(self, request):
        events = Event.objects.all()
        return render(request, 'calendar/calendar.html', {'events': events})


class AddEventView(LoginRequiredMixin, View):
    def get(self, request):
        initial_data = {}
        date = request.GET.get('date')
        if date:
            initial_data['start_time'] = f"{date}T18:00"
            initial_data['end_time'] = f"{date}T19:00"

        form = EventForm(initial=initial_data)
        return render(request, 'calendar/add_event.html', {'form': form})

    def post(self, request):
        form = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.user = request.user
            event.save()
            return redirect('calendar')
        return render(request, 'calendar/add_event.html', {'form': form})


class EventDetailView(View):
    def get(self, request, pk):
        event = get_object_or_404(Event, id=pk)
        return render(request, 'calendar/event_detail.html', {'event': event})


class EventEditView(UserPassesTestMixin, View):
    def test_func(self):
        pk = self.kwargs.get('pk')
        event = get_object_or_404(Event, pk=pk)
        return self.request.user == event.user

    def get(self, request, pk):
        event = get_object_or_404(Event, pk=pk)
        form = EventEditForm(instance=event)
        return render(request, 'calendar/edit_event.html', {'form': form, 'event': event})

    def post(self, request, pk):
        event = get_object_or_404(Event, pk=pk)
        form = EventEditForm(request.POST, instance=event)
        if form.is_valid():
            form.save()
            return redirect('calendar')
        return render(request, 'calendar/edit_event.html', {'form': form, 'event': event})


class EventDeleteView(UserPassesTestMixin, View):
    def test_func(self):
        pk = self.kwargs.get('pk')
        event = get_object_or_404(Event, pk=pk)
        return self.request.user == event.user

    def get(self, request, pk):
        event = get_object_or_404(Event, pk=pk)
        return render(request, 'calendar/event_delete_confirm.html', {'event': event})

    def post(self, request, pk):
        event = get_object_or_404(Event, pk=pk)
        event.delete()
        return redirect('calendar')

templates/calendar/add_event.html
{% extends 'base.html' %}
{% block title %}Dodaj Wydarzenie{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big big-add_form transparency">
            {% csrf_token %}
            <h1 class="big-title">Dodaj wydarzenie</h1>
            <br>
            {{ form.non_field_errors }}

            <div class="form-group-big">
                <label for="{{ form.title.id_for_label }}">Tytuł:</label>
                {{ form.title }}
                {% if form.title.errors %}
                    <br>
                    <span class="text-danger">{{ form.title.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="{{ form.start_time.id_for_label }}">Czas rozpoczęcia:</label>
                {{ form.start_time }}
                {% if form.start_time.errors %}
                    <br>
                    <span class="text-danger">{{ form.start_time.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="{{ form.end_time.id_for_label }}">Czas zakończenia:</label>
                {{ form.end_time }}
                {% if form.end_time.errors %}
                    <br>
                    <span class="text-danger">{{ form.end_time.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="{{ form.description.id_for_label }}">Opis:</label>
                {{ form.description }}
                {% if form.description.errors %}
                    <br>
                    <span class="text-danger">{{ form.description.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big centered">
                <button type="submit" class="btn-inline">Dodaj</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/calendar/calendar.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Kalendarz{% endblock %}
{% block content %}
    <h1 class="big-title">Kalendarz</h1>

    <div class="filter-and-add">
        <a href="{% url 'add_event' %}" class="btn-add">Dodaj wydarzenie</a>
    </div>

    <div id="calendar"></div>

    <script>
        // Passing events data to the external JS file
        var calendarEvents = [
            {% for event in events %}
                {
                    title: '{{ event.title }} ({{ event.user.username }})',
                    id: '{{ event.id }}',
                    start: '{{ event.start_time|date:"c" }}',
                    end: '{{ event.end_time|date:"c" }}',
                    extendedProps: {
                        duration: '{{ event.duration }}'
                    }
                },
            {% endfor %}
        ];
        var addEventUrl = "{% url 'add_event' %}";
    </script>
    <script src="{% static 'js/calendar.js' %}"></script>
{% endblock %}

templates/calendar/edit_event.html
{% extends 'base.html' %}
{% block title %}Edytuj Wydarzenie{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big big-add_form transparency">
            {% csrf_token %}
            <h1 class="big-title">Edytuj wydarzenie</h1>
            <br>
            {{ form.non_field_errors }}

            <div class="form-group-big">
                <label for="{{ form.title.id_for_label }}">Tytuł:</label>
                {{ form.title }}
                {% if form.title.errors %}
                    <br>
                    <span class="text-danger">{{ form.title.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="{{ form.start_time.id_for_label }}">Czas rozpoczęcia:</label>
                <!-- Ensure start_time field value is formatted correctly -->
                <input type="datetime-local" name="start_time" id="id_start_time"
                       value="{{ event.start_time|date:'Y-m-d\TH:i' }}" required>
                {% if form.start_time.errors %}
                    <br>
                    <span class="text-danger">{{ form.start_time.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="{{ form.end_time.id_for_label }}">Czas zakończenia:</label>
                <!-- Ensure end_time field value is formatted correctly -->
                <input type="datetime-local" name="end_time" id="id_end_time"
                       value="{{ event.end_time|date:'Y-m-d\TH:i' }}" required>
                {% if form.end_time.errors %}
                    <br>
                    <span class="text-danger">{{ form.end_time.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="{{ form.description.id_for_label }}">Opis:</label>
                {{ form.description }}
                {% if form.description.errors %}
                    <br>
                    <span class="text-danger">{{ form.description.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big centered">
                <button type="submit" class="btn-inline">Zapisz zmiany</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/calendar/event_delete_confirm.html
{% extends 'base.html' %}
{% block title %}Usuń Wydarzenie{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big transparency">
            <h1 class="big-title">Usunięcie Wydarzenia</h1>
            <p>Czy jesteś pewien/pewna, że chcesz usunąć wydarzenie:</p>
            <h2 class="centered">{{ event.title }}</h2>
            {% csrf_token %}
            <div class="button-container">
                <button type="submit" class="btn-inline btn-confirm">Potwierdzam</button>
                <a href="{% url 'calendar' %}" class="btn-inline-cancel">Powrót do kalendarza</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/calendar/event_detail.html
{% extends 'base.html' %}
{% block title %}Wydarzenie{% endblock %}
{% block content %}
    <div class="training-list-item transparency">
        <h1 class="big-title">{{ event.title }}</h1>
        <p><strong>Początek:</strong> {{ event.start_time }}</p>
        <p><strong>Koniec:</strong> {{ event.end_time }}</p>
        <p><strong>Opis:</strong> {{ event.description }}</p>
            <div class="training-buttons centered">
                <a href="{% url 'event_edit' event.id %}" class="btn-edit">Edytuj</a>
                <a href="{% url 'event_delete' event.id %}" class="btn-delete">Usuń Wydarzenie</a>
            </div>
    </div>
{% endblock %}