config/urls.py
from django.contrib import admin
from django.urls import path, include
from trainingplans import views
from trainingplans.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('treningikonne/', include("trainingplans.urls")),
    path('kalendarz/', include("calendar_.urls")),
]

trainingplans/urls.py
from django.contrib import admin
from django.urls import path
from trainingplans import views
from trainingplans.views import HomeView

urlpatterns = [
    path('testy/', views.TestView.as_view(), name='test'),
    path('training_list/', views.TrainingListView.as_view(), name='training_list'),
    path('training_detail/<int:pk>/', views.TrainingDetailView.as_view(), name='training_detail'),
    path('training_add', views.AddTrainingView.as_view(), name='training_add'),
    path('training_delete/<int:pk>/', views.DeleteTrainingView.as_view(), name='training_delete'),
    path('training_edit/<int:pk>/', views.EditTrainingView.as_view(), name='training_edit'),
    path('plan_list/', views.PlanListView.as_view(), name='plan_list'),
    path('plan_detail/<int:pk>/', views.PlanDetailView.as_view(), name='plan_detail'),
    path('plan_add/', views.AddPlanView.as_view(), name='plan_add'),
    path('plan_delete/<int:pk>/', views.DeletePlanView.as_view(), name='plan_delete'),
    path('plan_edit/<int:pk>/', views.EditPlanView.as_view(), name='plan_edit'),
    path('horse_list/', views.HorseListView.as_view(), name='horse_list'),
    path('horse_detail/<int:pk>/', views.HorseDetailView.as_view(), name='horse_detail'),
    path('horse_add/', views.AddHorseView.as_view(), name='horse_add'),
    path('horse_delete/<int:pk>/', views.DeleteHorseView.as_view(), name='horse_delete'),
    path('horse_edit/<int:pk>/', views.EditHorseView.as_view(), name='horse_edit'),
    path('trainer_list/', views.TrainerListView.as_view(), name='trainer_list'),
    path('trainer_detail/<int:pk>/', views.TrainerDetailView.as_view(), name='trainer_detail'),
    path('trainer_add/', views.AddTrainerView.as_view(), name='trainer_add'),
    path('trainer_delete/<int:pk>/', views.DeleteTrainerView.as_view(), name='trainer_delete'),
    path('trainer_edit/<int:pk>/', views.EditTrainerView.as_view(), name='trainer_edit'),
    path('add_training_to_plan/<int:pk>/', views.TrainingToPlanAdd.as_view(), name='add_training_to_plan'),
    path('add_training_to_any_plan/', views.TrainingToAnyPlanAdd.as_view(), name='add_training_to_any_plan'),
    path('delete_training_from_plan/<int:pk>/', views.DeleteTrainingFromPlanView.as_view(), name='delete_training_from_plan'),
]

trainingplans/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class TrainingType(models.TextChoices):
    SKOKOWY = 'SK', 'Skokowy'
    UJEŻDŻENIOWY = 'UJ', 'Ujeżdżeniowy'
    LONŻA = 'LO', 'Lonża'
    PRACA_Z_ZIEMI = 'PZ', 'Praca z ziemi'
    TEREN = 'TE', 'Teren'
    CROSS = 'CR', 'Cross'


class Training(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(
        max_length=2,
        choices=TrainingType.choices,
    )
    description = models.TextField()
    length = models.IntegerField()

    def __str__(self):
        return f"{self.name} typu {self.get_type_display()} o długości {self.length} min"


class Plan(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    trainings = models.ManyToManyField(Training, through='TrainingPlan')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class TrainingPlanDay(models.TextChoices):
    PONIEDZIAŁEK = 'PN', 'Poniedziałek'
    WTOREK = 'WT', 'Wtorek'
    ŚRODA = 'SR', 'Środa'
    CZWARTEK = 'CZ', 'Czwartek'
    PIĄTEK = 'PT', 'Piątek'
    SOBOTA = 'SB', 'Sobota'
    NIEDZIELA = 'ND', 'Niedziela'


class Horse(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Trainer(models.Model):
    name = models.CharField(max_length=100)
    training_type = models.CharField(
        max_length=2,
        choices=TrainingType.choices
    )
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.name} trening: {self.get_training_type_display()}"


class TrainingPlan(models.Model):
    training = models.ForeignKey(Training, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)
    day = models.CharField(
        max_length=2,
        choices=TrainingPlanDay.choices,
        default=TrainingPlanDay.PONIEDZIAŁEK
    )
    time = models.TimeField()
    horse = models.ForeignKey(Horse, on_delete=models.CASCADE)
    trainer = models.ForeignKey(Trainer, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.plan.name} - {self.training.name} - {self.training.type} w {self.get_day_display()} o {self.time}"

trainingplans/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import TemplateView
from django.contrib import messages

from trainingplans import models
from trainingplans.forms import TrainingPlanForm, TrainingToAnyPlanForm, TrainerForm
from trainingplans.models import Training, TrainingType, Plan, Horse, Trainer, TrainingPlan, TrainingPlanDay


def pagination(request, queryset, items_per_page=5):
    paginator = Paginator(queryset, items_per_page)  # we define what should be paginated and how many elements per page
    page_number = request.GET.get('page', 1)  # in case there is no page select 1
    try:
        page_object = paginator.page(page_number)
    except PageNotAnInteger:  # handling annoying user manually changing stuff
        page_object = paginator.page(1)
    except EmptyPage:  # again, annoying user, when out of range page
        page_object = paginator.page(paginator.num_pages)
    return page_object


# Create your views here.
class HomeView(View):
    def get(self, request):
        return render(request, 'trainingplans/homepage.html')


class TestView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'trainingplans/test.html')


class TrainingListView(View):
    def get(self, request):
        name = request.GET.get('name', '')
        training_type = request.GET.get('training_type', '')
        min_length = request.GET.get('min_length', '0')
        trainings = Training.objects.all()
        training_type_choices = TrainingType.choices

        # Filtering
        if name:
            trainings = trainings.filter(name__icontains=name)
        if training_type:
            trainings = trainings.filter(type__icontains=training_type)
        try:
            min_length = int(min_length)
            if min_length >= 0:
                trainings = trainings.filter(length__gte=min_length)
            elif min_length < 0:
                raise ValueError("Długość treningu nie może być ujemna.")
        except ValueError as e:
            messages.error(request, str(e))

        # Pagination
        page_object = pagination(request, trainings)

        return render(request, 'trainingplans/TrainingList.html', {
            'page_object': page_object,  # Pass paginated queryset to template
            'training_type_choices': training_type_choices
        })


class TrainingDetailView(View):
    def get(self, request, pk):
        training = get_object_or_404(Training, pk=pk)
        return render(request, 'trainingplans/TrainingDetail.html', {'training': training})


class AddTrainingView(LoginRequiredMixin, View):
    def get(self, request):
        training_type_choices = TrainingType.choices
        return render(request, 'trainingplans/AddTraining.html', {'training_type_choices': training_type_choices})

    def post(self, request):
        name = request.POST.get('name')
        training_type = request.POST.get('training_type')
        length = request.POST.get('length')
        description = request.POST.get('description')
        training_type_choices = TrainingType.choices

        errors = {}
        if not name:
            errors['name'] = 'Nazwa wymagana!'
        if not training_type:
            errors['training_type'] = 'Typ wymagany!'
        if not length:
            errors['length'] = 'Długość wymagana!'
        if not description:
            errors['description'] = 'Opis wymagany!'
        if errors:
            return render(request, 'trainingplans/AddTraining.html', {
                'errors': errors,
                'name': name,
                'training_type': training_type,
                'length': length,
                'description': description,
                'training_type_choices': training_type_choices
            })

        try:
            training = models.Training.objects.create(
                name=name,
                type=training_type,
                length=length,
                description=description
            )
            return redirect('training_detail', pk=training.pk)

        except Exception as e:
            return render(request, 'trainingplans/AddTraining.html', {
                'errors': e,
                'training_type_choices': training_type_choices
            })


class DeleteTrainingView(LoginRequiredMixin, View):
    def get(self, request, pk):
        training = get_object_or_404(Training, pk=pk)
        return render(request, 'trainingplans/DeleteConfirmation.html', {'training': training})

    def post(self, request, pk):
        training = get_object_or_404(Training, pk=pk)
        training.delete()
        return redirect('training_list')


class EditTrainingView(LoginRequiredMixin, View):
    def get(self, request, pk):
        training = get_object_or_404(Training, pk=pk)
        training_type_choices = TrainingType.choices
        return render(request, 'trainingplans/TrainingEdit.html', {
            'training': training,
            'training_type_choices': training_type_choices
        })

    def post(self, request, pk):
        name = request.POST.get('name')
        training_type = request.POST.get('training_type')
        length = request.POST.get('length')
        description = request.POST.get('description')
        training_type_choices = TrainingType.choices
        training = models.Training.objects.get(pk=pk)

        errors = {}
        if not name:
            errors['name'] = 'Nazwa wymagana!'
        if not training_type:
            errors['training_type'] = 'Typ wymagany!'
        if not length:
            errors['length'] = 'Długość wymagana!'
        if not description:
            errors['description'] = 'Opis wymagany!'
        if errors:
            return render(request, 'trainingplans/TrainingEdit.html', {
                'errors': errors,
                'name': name,
                'training_type': training_type,
                'length': length,
                'description': description,
                'training_type_choices': training_type_choices,
                'training': training
            })

        try:
            training.name = name
            training.type = training_type
            training.length = length
            training.description = description
            training.save()
            return redirect('training_detail', pk=training.pk)

        except Exception as e:
            return render(request, 'trainingplans/TrainingEdit.html', {
                'errors': e,
                'training_type_choices': training_type_choices
            })


class PlanListView(LoginRequiredMixin, View):
    def get(self, request):
        name = request.GET.get('name')
        plans = models.Plan.objects.filter(user=request.user)
        if name:
            plans = plans.filter(name__icontains=name)
        # see pagination function for some explanation of pagination
        page_object = pagination(request, plans)
        return render(request, 'trainingplans/PlanList.html', {'page_object': page_object})


class PlanDetailView(UserPassesTestMixin, View):
    def test_func(self):
        plan = models.Plan.objects.get(pk=self.kwargs['pk'])
        return self.request.user == plan.user

    def get(self, request, pk):
        plan = get_object_or_404(Plan, pk=pk)
        days_plan = TrainingPlan.objects.filter(plan=plan).order_by('day', 'time')

        # We group trainings by the days
        trainings_by_day = {day.label: [] for day in TrainingPlanDay}
        for training_plan in days_plan:
            day = training_plan.get_day_display()
            trainings_by_day[day].append(training_plan)

        # We show only days that have something happening in them (so there is a training in those days)
        trainings_by_day = {day: trainings for day, trainings in trainings_by_day.items() if trainings}

        return render(request, 'trainingplans/PlanDetail.html', {
            'plan': plan,
            'trainings_by_day': trainings_by_day,
        })


class AddPlanView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'trainingplans/AddPlan.html')

    def post(self, request):
        name = request.POST.get('name')
        description = request.POST.get('description')
        errors = {}
        if not name:
            errors['name'] = 'Nazwa wymagana!'
        if not description:
            errors['description'] = 'Opis wymagany!'
        if errors:
            return render(request, 'trainingplans/AddPlan.html', {
                'errors': errors,
                'name': name,
                'description': description,
            })

        try:
            plan = models.Plan.objects.create(
                name=name,
                description=description,
                user_id=request.user.id,
            )
            return redirect('plan_detail', pk=plan.pk)

        except Exception as e:
            return render(request, 'trainingplans/AddPlan.html', {
                'errors': e,
            })


class DeletePlanView(UserPassesTestMixin, View):
    def test_func(self):
        plan = models.Plan.objects.get(pk=self.kwargs['pk'])
        return self.request.user == plan.user

    def get(self, request, pk):
        plan = get_object_or_404(Plan, pk=pk)
        return render(request, 'trainingplans/DeletePlanConfirmation.html', {'plan': plan})

    def post(self, request, pk):
        plan = get_object_or_404(Plan, pk=pk)
        plan.delete()
        return redirect('plan_list')


class EditPlanView(UserPassesTestMixin, View):
    def test_func(self):
        plan = models.Plan.objects.get(pk=self.kwargs['pk'])
        return self.request.user == plan.user

    def get(self, request, pk):

templates/trainingplans/AddPlan.html
{% extends 'base.html' %}
{% block title %}Dodaj Plan{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big big-add_form transparency">
            {% csrf_token %}
            <h1 class="big-title">Nowy Plan</h1>
            <br>
            <div class="form-group-big">
                <label for="name">Nazwa:</label>
                <input type="text" id="name" name="name" value="{{ name }}" placeholder="Nazwa Planu">
                {% if errors.name %}
                    <br>
                    <span class="text-danger">{{ errors.name }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="description">Opis:</label>
                <textarea id="description" name="description" placeholder="Dodaj Opis" rows="5">{{ description }}</textarea>
                {% if errors.description %}
                    <br>
                    <span class="text-danger">{{ errors.description }}</span>
                {% endif %}
            </div>

            <div class="form-group-big centered">
                <button type="submit" class="btn-inline">Dodaj</button>
            </div>

        </form>
    </div>
{% endblock %}

templates/trainingplans/AddTrainer.html
{% extends 'base.html' %}
{% block title %}Dodaj Trenera{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big big-add_form transparency">
            {% csrf_token %}
            <h1 class="big-title">Nowy Trener</h1>
            <br>
            {{ form.non_field_errors }}

            <div class="form-group-big">
                <label for="{{ form.name.id_for_label }}">Imię i Nazwisko:</label>
                {{ form.name }}
                {% if form.name.errors %}
                    <br>
                    <span class="text-danger">{{ form.name.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="{{ form.training_type.id_for_label }}">Typ treningu:</label>
                {{ form.training_type }}
                {% if form.training_type.errors %}
                    <br>
                    <span class="text-danger">{{ form.training_type.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="{{ form.description.id_for_label }}">Opis:</label>
                {{ form.description }}
                {% if form.description.errors %}
                    <br>
                    <span class="text-danger">{{ form.description.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big centered">
                <button type="submit" class="btn-inline">Dodaj</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/trainingplans/AddTrainingToPlan.html
{% extends 'base.html' %}
{% block title %}Dodaj Trening Do Planu{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big big-add_form transparency">
            {% csrf_token %}
            <h1 class="big-title">Nowy Trening do Planu: {{ plan.name }}</h1>
            <br>
            {{ form.non_field_errors }}

            <div class="form-group-big">
                <label for="id_training">Trening:</label>
                {{ form.training }}
                {% if form.training.errors %}
                    <br>
                    <span class="text-danger">{{ form.training.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="id_day">Dzień:</label>
                {{ form.day }}
                {% if form.day.errors %}
                    <br>
                    <span class="text-danger">{{ form.day.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="id_time">Godzina:</label>
                {{ form.time }}
                {% if form.time.errors %}
                    <br>
                    <span class="text-danger">{{ form.time.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="id_horse">Koń:</label>
                {{ form.horse }}
                {% if form.horse.errors %}
                    <br>
                    <span class="text-danger">{{ form.horse.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="id_trainer">Trener:</label>
                {{ form.trainer }}
                {% if form.trainer.errors %}
                    <br>
                    <span class="text-danger">{{ form.trainer.errors }}</span>
                {% endif %}
            </div>

            <div class="form-group-big centered">
                <button type="submit" class="btn-inline">Dodaj</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/trainingplans/DeleteConfirmation.html
{% extends 'base.html' %}
{% block title %}Usuń Trening{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big transparency">
            <h1 class="big-title">Usunięcie trening</h1>
            <p>Czy jesteś pewien/pewna, że chcesz usunąć trening: </p>
            <h2 class="centered">{{ training.name }}</h2>
            {% csrf_token %}
            <div class="button-container">
                <button type="submit" class="btn-inline btn-confirm">Potwierdzam</button>
                <a href="{% url 'training_list' %}" class="btn-inline-cancel">Powrót do listy treningów</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/trainingplans/DeleteHorseConfirmation.html
{% extends 'base.html' %}
{% block title %}Usuń Konia{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big transparency">
            <h1 class="big-title">Usunięcie Konia</h1>
            <p>Czy jesteś pewien/pewna, że chcesz usunąć konia: </p>
            <h2 class="centered">{{ horse.name }}</h2>
            {% csrf_token %}
            <div class="button-container">
                <button type="submit" class="btn-inline btn-confirm">Potwierdzam</button>
                <a href="{% url 'horse_list' %}" class="btn-inline-cancel">Powrót do listy koni</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/trainingplans/DeletePlanConfirmation.html
{% extends 'base.html' %}
{% block title %}Usuń Plan{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big transparency">
            <h1 class="big-title">Usunięcie Planu</h1>
            <p>Czy jesteś pewien/pewna, że chcesz usunąć plan: </p>
            <h2 class="centered">{{ plan.name }}</h2>
            {% csrf_token %}
            <div class="button-container">
                <button type="submit" class="btn-inline btn-confirm">Potwierdzam</button>
                <a href="{% url 'plan_list' %}" class="btn-inline-cancel">Powrót do listy planów</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/trainingplans/DeleteTrainerConfirmation.html
{% extends 'base.html' %}
{% block title %}Usuń Trenera{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big transparency">
            <h1 class="big-title">Usunięcie Trenera</h1>
            <p>Czy jesteś pewien/pewna, że chcesz usunąć trenera:</p>
            <h2 class="centered">{{ trainer.name }}</h2>
            {% csrf_token %}
            <div class="button-container">
                <button type="submit" class="btn-inline btn-confirm">Potwierdzam</button>
                <a href="{% url 'trainer_list' %}" class="btn-inline-cancel">Powrót do listy trenerów</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/trainingplans/HorseDetail.html
{% extends 'base.html' %}
{% block title %}Szczegóły Konia{% endblock %}
{% block content %}
    <div class="filter-and-add">
        <a href="{% url 'horse_add' %}" class="btn-add">Nowy Koń</a>
    </div>
    <div></div>
    <div class="training-list-item transparency">
        <h1 class="big-title">Szczegóły Konia</h1>
        <div class="training-header">
            <h2>{{ horse.name }}</h2>
            <div class="training-buttons">
                <a href="{% url 'horse_edit' horse.id %}" class="btn-edit">Edytuj</a>
                <a href="{% url 'horse_delete' horse.id %}" class="btn-delete">Usuń</a>
            </div>
        </div>
        <p>Opis:<br>{{ horse.description }}</p>
    </div>

{% endblock %}

templates/trainingplans/HorseEdit.html
{% extends 'base.html' %}
{% block title %}Edytuj Konia{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big big-add_form transparency">
            {% csrf_token %}
            <h1 class="big-title">Edycja Konia {{ horse.name }}</h1>
            <br>
            <div class="form-group-big">
                <label for="name">Imię:</label>
                <input type="text" id="name" name="name" value="{{ name|default:horse.name }}" placeholder="Imię Konia">
                {% if errors.name %}
                    <br>
                    <span class="text-danger">{{ errors.name }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="description">Opis:</label>
                <textarea id="description" name="description" placeholder="Dodaj Opis" rows="5">{{ description|default:horse.description }}</textarea>
                {% if errors.description %}
                    <br>
                    <span class="text-danger">{{ errors.description }}</span>
                {% endif %}
            </div>

            <div class="form-group-big centered">
                <button type="submit" class="btn-inline">Edytuj</button>
            </div>

        </form>
    </div>
{% endblock %}

templates/trainingplans/HorseList.html
{% extends 'base.html' %}
{% block title %}Lista Koni{% endblock %}
{% block content %}

    <div class="filter-and-add">
        <a href="{% url 'horse_add' %}" class="btn-add">Nowy Koń</a>
    </div>

    <form method="GET" class="form-container-inline transparency">
        
        <div class="form-group-inline">
            <h2>Filtruj</h2>
            <label for="name">Imię:</label>
            <input type="text" id="name" name="name" placeholder="Imię Konia">
        </div>
        <div class="form-group-inline">
            <button type="submit" class="btn-inline">Filtruj</button>
        </div>
    </form>

    <h1 class="big-title">Lista Koni</h1>

    <div class="training-list transparency">
        {% for horse in page_object %}
            <div class="training-list-item">
                <div class="training-header">
                    <h2>{{ horse.name }}</h2>
                    <div class="training-buttons">
                        <a href="{% url 'horse_detail' horse.id %}" class="btn-detail">Szczegóły</a>
                        <a href="{% url 'horse_edit' horse.id %}" class="btn-edit">Edytuj</a>
                        <a href="{% url 'horse_delete' horse.id %}" class="btn-delete">Usuń</a>
                    </div>
                </div>
                <p>Opis:<br>{{ horse.description }}</p>
            </div>
        {% endfor %}

        <div>
            {% if page_object.has_previous %}
                <a href="?page=1">&laquo; Pierwsza</a>
                <a href="?page={{ page_object.previous_page_number }}">Poprzednia</a>
            {% endif %}

            <span>Strona {{ page_object.number }} z {{ page_object.paginator.num_pages }}</span>

            {% if page_object.has_next %}
                <a href="?page={{ page_object.next_page_number }}">Następna</a>
                <a href="?page={{ page_object.paginator.num_pages }}">Ostatnia &raquo;</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/trainingplans/PlanEdit.html
{% extends 'base.html' %}
{% block title %}Edycja Planu{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big big-add_form transparency">
            {% csrf_token %}
            <h1 class="big-title">Edycja Planu {{ plan.name }}</h1>
            <br>
            <div class="form-group-big">
                <label for="name">Nazwa:</label>
                <input type="text" id="name" name="name" value="{{ name|default:plan.name }}" placeholder="Nazwa Planu">
                {% if errors.name %}
                    <br>
                    <span class="text-danger">{{ errors.name }}</span>
                {% endif %}
            </div>


            <div class="form-group-big">
                <label for="description">Opis:</label>
                <textarea id="description" name="description" placeholder="Dodaj Opis" rows="5">{{ description|default:plan.description }}</textarea>
                {% if errors.description %}
                    <br>
                    <span class="text-danger">{{ errors.description }}</span>
                {% endif %}
            </div>

            <div class="form-group-big centered">
                <button type="submit" class="btn-inline">Edytuj</button>
            </div>

        </form>
    </div>
{% endblock %}

templates/trainingplans/TrainerEdit.html
{% extends 'base.html' %}
{% block title %}Edycja Trenera{% endblock %}
{% block content %}
    <div class="centered">
        <form method="POST" class="form-container-big big-add_form transparency">
            {% csrf_token %}
            <h1 class="big-title">Edycja Trenera {{ trainer.name }}</h1>
            <br>
            <div class="form-group-big">
                <label for="name">Imię i Nazwisko:</label>
                <input type="text" id="name" name="name" value="{{ name|default:trainer.name }}" placeholder="Imię/Nazwisko Trenera">
                {% if errors.name %}
                    <br>
                    <span class="text-danger">{{ errors.name }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="training_type">Typ treningu:</label>
                <select id="training_type" name="training_type" style="height: 30px">
                    <option value="">Wybierz typ treningu</option>
                    {% for choice in training_type_choices %}
                        <option value="{{ choice.0 }}" {% if choice.0 == training_type|default:trainer.training_type %}
                                selected {% endif %}>{{ choice.1 }}</option>
                    {% endfor %}
                </select>
                {% if errors.training_type %}
                    <br>
                    <span class="text-danger">{{ errors.training_type }}</span>
                {% endif %}
            </div>

            <div class="form-group-big">
                <label for="description">Opis:</label>
                <textarea id="description" name="description" placeholder="Dodaj Opis" rows="5">{{ description|default:trainer.description }}</textarea>
                {% if errors.description %}
                    <br>
                    <span class="text-danger">{{ errors.description }}</span>
                {% endif %}
            </div>

            <div class="form-group-big centered">
                <button type="submit" class="btn-inline">Edytuj</button>
            </div>

        </form>
    </div>
{% endblock %}

templates/trainingplans/test.html
{% extends "base.html" %}
{% block content %}
    <h1>Testy</h1>
    <p> to są zwyczajne testy</p>

    <ul>
        <li>fajna lista bulwo</li>
        <li>jeszcze jeden element</li>
    </ul>
{% endblock %}